#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jul  5 09:52:02 2018

@author: christinakronser
"""


import google.cloud.language
import os
os.environ["GOOGLE_APPLICATION_CREDENTIALS"]="/Users/christinakronser/Downloads/My First Project-522341c822f9.json"


# Create a Language client.
language_client = google.cloud.language.LanguageServiceClient()

text = 'I was happy and smiled the whole time but then something terrible happened. It made me sad and I angry at the same time. I cried a lot and thoguht about dying'
document = google.cloud.language.types.Document(
    content=text,
    type=google.cloud.language.enums.Document.Type.PLAIN_TEXT)

# Use Language to detect the sentiment of the text.
response = language_client.analyze_sentiment(document=document)
sentiment = response.document_sentiment

print(u'Text: {}'.format(text))
print(u'Sentiment: Score: {}, Magnitude: {}'.format(
    sentiment.score, sentiment.magnitude))

